/*
Most of this code was generated by Bing using the following prompt:

Write a set of JavaScript functions to perform the following task.
Generate random mock data for an application
that tracks leftover volume in beer kegs.
The mock data is a JSON object that has unix timestamps in seconds as keys
and volumes as values in liters.
The resolution of the volume measurement is 0.05 liters.
Note that the leftover volume is only decreasing over the time.
The volume is decreased by performing pours,
which decrease the volume by 0.2 - 0.5 liters each time randomly.
A single pour takes about 40-150 seconds per liter,
and this speed is determined once at the beginning.
The main functions should have two parameters:
the initial volume and the current date.
The data should go back around 8 weeks from the current date.
Pours mostly happen on Friday, Saturday and Sunday.
On each of these days there should be 1-3, 3-5, and 1-5 pours per day, respectively.
Pours happen between 4PM and midnight.
On 2 random weeks, a single pour happens either on Monday or Wednesday
in the same time range specified above.
Output the JavaScript source code.
*/

import merge from "lodash.merge";

// A function to generate a random number between min and max
function random(min, max) {
  return Math.random() * (max - min) + min;
}

// A function to generate a random integer between min and max
function randomInt(min, max) {
  // note: this was changed to the implementation from MDN, see:
  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#getting_a_random_integer_between_two_values
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1) + min);
}

// A function to round a number to the nearest multiple of step
function roundToStep(number, step) {
  return Math.round(number / step) * step;
}

// note: the original code was incorrect so this was manually implemented
function makePour(leftoverVolume, pourTime, pourSpeed, pourVolume) {
  const numPoints = Math.floor(pourVolume / 0.05);
  const secondsPerPoint = (pourSpeed * pourVolume) / numPoints;
  return merge(
    ...[...Array(numPoints).keys()].map((i) => {
      const obj = {};
      pourTime.setSeconds(pourTime.getSeconds() + secondsPerPoint);
      const key = (pourTime.getTime() / 1000).toString();
      obj[key] = leftoverVolume - (i + 1) * 0.05;
      return obj;
    })
  );
}

// A function to generate mock data for leftover volume in beer kegs
export default function createTapMockData(bottlingVolume, bottlingDate) {
  // Initialize the mock data object
  let mockData = {};
  mockData[(new Date(bottlingDate).getTime() / 1000).toString()] =
    bottlingVolume;

  // Calculate the start date as 8 weeks before the current date
  let currentDate = new Date();
  let startDate = new Date(currentDate);
  startDate.setDate(startDate.getDate() - 8 * 7);

  // Calculate the pour speed as a random number between 40 and 80 seconds per liter
  let pourSpeed = random(40, 150);

  // Initialize the leftover volume as the initial volume
  let leftoverVolume = bottlingVolume;

  // Loop through each week from the start date to the current date
  for (
    let week = startDate;
    week < currentDate;
    week.setDate(week.getDate() + 7)
  ) {
    // Generate a random number of pours for Friday, Saturday and Sunday
    let fridayPours = randomInt(1, 3);
    let saturdayPours = randomInt(3, 5);
    let sundayPours = randomInt(1, 5);

    // Generate a random weekday pour for two random weeks
    let weekdayPour = false;
    let weekdayPourDay;
    let weekdayPourPours;
    if (randomInt(1, 4) === 1) {
      weekdayPour = true;
      // Choose either Monday or Wednesday as the weekday pour day
      weekdayPourDay = randomInt(0, 1) === 0 ? "Monday" : "Wednesday";
      // Generate a random number of pours for the weekday pour day
      weekdayPourPours = randomInt(1, 1);
    }

    // Loop through each day of the week
    for (
      let day = new Date(week);
      day < currentDate;
      day.setDate(day.getDate() + 1)
    ) {
      // Get the day name as a string
      let dayName = day.toLocaleDateString("en-US", { weekday: "long" });

      // Initialize the number of pours for the day as zero
      let pours = 0;

      // Set the number of pours for the day based on the day name and the weekday pour flag
      if (dayName === "Friday") {
        pours = fridayPours;
      } else if (dayName === "Saturday") {
        pours = saturdayPours;
      } else if (dayName === "Sunday") {
        pours = sundayPours;
      } else if (weekdayPour && dayName === weekdayPourDay) {
        pours = weekdayPourPours;
      }

      // Generate a random pour time between 4PM and midnight
      // modified to ensure pours are happening after each other
      let pourTime = new Date(day);
      pourTime.setHours(16);
      pourTime.setMinutes(0);
      pourTime.setSeconds(0);

      let minutesPerPour = ((24 - 16) * 60) / pours;

      // Loop through each pour for the day
      for (let i = 0; i < pours; i++) {
        let pourMinutesOffset = randomInt(3, minutesPerPour);
        pourTime.setMinutes(pourTime.getMinutes() + pourMinutesOffset);

        // Generate a random pour volume between 0.2 and 0.5 liters
        let pourVolume = roundToStep(random(0.2, 0.5), 0.05);

        if (leftoverVolume - pourVolume < 0) {
          break;
        }

        // note: this part was re-implemented manually
        mockData = merge(
          mockData,
          makePour(leftoverVolume, pourTime, pourSpeed, pourVolume)
        );

        leftoverVolume -= pourVolume;
      }
    }
  }

  // Return the mock data object
  return mockData;
}
